import type { Connection, Project, ReusableAsset } from "./types";

/**
 * SAMPLE DATA — believable placeholders so the map has shape.
 * Every record has `sample: true`. Replace one project at a time via Intake.
 * Numbers here are illustrative, not real results.
 */

const img = (name: string) => `./img/${name}.webp`;
const orb = (name: string) => `./orb/${name}.webp`;

export const reusableAssets: ReusableAsset[] = [
  {
    id: "effect-kit",
    name: "Scroll & 3D Effect Kit",
    type: "effect",
    projectIds: ["portfolio", "extractor", "pilot"],
    note: "GSAP ScrollTrigger hero, pinned chapters, text reveals, depth parallax.",
    onMap: { radius: 500, angle: 270 },
    orb: orb("moon-b"),
  },
  {
    id: "prompt-library",
    name: "Prompt Library",
    type: "prompt",
    projectIds: ["vault", "extractor", "aiconcepts"],
    note: "38 working prompts pulled out of past Claude and ChatGPT chats.",
    onMap: { radius: 820, angle: 0 },
    orb: orb("moon-a"),
  },
  {
    id: "pitch-templates",
    name: "Pitch & Proposal Templates",
    type: "template",
    projectIds: ["sponsorship", "nonprofit", "pilot"],
    note: "Sponsor decks, tier sheets, client proposals, one-pagers.",
    onMap: { radius: 820, angle: 180 },
    orb: orb("moon-c"),
  },
  {
    id: "brand-editorial",
    name: "Dark Editorial Visual System",
    type: "brand",
    projectIds: ["portfolio", "vault"],
    note: "Type pairing, grain, depth and motion rules shared by studio work.",
  },
  {
    id: "dossier-template",
    name: "Project Dossier Template",
    type: "template",
    projectIds: ["vault"],
    note: "The nine intake questions plus the ten-point stress test.",
  },
  {
    id: "impact-sheet",
    name: "Impact One-Pager",
    type: "template",
    projectIds: ["nonprofit", "sponsorship"],
    note: "Outcome-first single page for partners and sponsors.",
  },
  {
    id: "curriculum",
    name: "6-Week Web Curriculum",
    type: "content",
    projectIds: ["nonprofit"],
    note: "Session plans, starter repo, and mentor notes.",
  },
  {
    id: "email-sequence",
    name: "Sponsor Email Sequence",
    type: "content",
    projectIds: ["sponsorship"],
    note: "Four-message outreach and follow-up sequence.",
  },
];

export const projects: Project[] = [
  /* ---------------------------------------------------------------- */
  {
    id: "vault",
    index: 1,
    name: "Project Intelligence Vault",
    oneLiner:
      "A private visual HQ that turns scattered chats, files and prototypes into decision-ready dossiers.",
    category: "Internal Tool",
    area: "Technology",
    status: "Prototyping",
    internalUse: true,
    readiness: 2,
    potential: 4,
    strategic: 5,
    cover: img("vault"),
    orb: orb("orb-vault"),
    media: [{ id: "m-vault-1", projectId: "vault", type: "image", src: img("vault"), caption: "Concept board" }],
    sources: [
      { id: "s-vault-1", projectId: "vault", kind: "folder", label: "Working folder", location: "~/Studio/vault/", isSourceOfTruth: true, lastVerified: "2026-09-20" },
      { id: "s-vault-2", projectId: "vault", kind: "git", label: "Prototype repo", location: "github.com/your-handle/studio-vault", isSourceOfTruth: true, lastVerified: "2026-09-22" },
      { id: "s-vault-3", projectId: "vault", kind: "chat", label: "Claude — “Vault requirements”", location: "claude.ai · Sep 2026", isSourceOfTruth: false, lastVerified: "2026-09-22" },
    ],
    whatItIs:
      "A spatial map of every project with a dossier for each: what exists, what's proven, what's reusable, and one next move.",
    audience:
      "You first. Later, possibly independent creators and small studios with too many half-finished projects.",
    problem:
      "Dozens of projects live across Claude, ChatGPT, Git and local folders with no shared view of what's proven, what's reusable, or what to do next.",
    whatExists: [
      "This prototype: Vault Map + Project Dossier with sample data",
      "Data model for projects, evidence, sources, assets and connections",
      "Nine-question intake list",
    ],
    couldBecome: "Your operating system for deciding what to build. A product for others only if evidence appears.",
    decisionNeeded: "How much to build before real projects are loaded.",
    evidence: [
      { id: "e-v1", projectId: "vault", kind: "prototype", verification: "verified", statement: "Vault Map + Dossier prototype runs with sample data.", sourceId: "s-vault-2", date: "2026-09-24" },
      { id: "e-v2", projectId: "vault", kind: "feedback", verification: "claimed", statement: "Roughly 6 hours last month spent hunting old chats for prompts and files (self-estimate, not tracked).", date: "2026-09-10" },
      { id: "e-v3", projectId: "vault", kind: "feedback", verification: "assumed", statement: "Other creators have the same problem and would pay for a tool like this.", date: "2026-09-22" },
    ],
    opportunity: {
      summary: "High personal leverage: every project you load makes cross-project reuse visible.",
      model: "None for now — internal tool. External model unexplored.",
      distribution: "Not applicable until it proves useful to you.",
      differentiation: "Evidence ledger and one-move recommendations, not just storage.",
    },
    stress: [
      { key: "problem", rating: "strong", basis: "evidence", note: "Felt weekly — searching chats and folders for past work." },
      { key: "audience", rating: "partial", basis: "judgment", note: "Clear for you. Unknown for anyone else." },
      { key: "proof", rating: "weak", basis: "evidence", note: "Prototype only. No real project loaded yet." },
      { key: "differentiation", rating: "unknown", basis: "none", note: "No competitor scan. Notion, Obsidian and Airtable templates overlap." },
      { key: "scope", rating: "partial", basis: "judgment", note: "Five views planned; risk of building all before using one." },
      { key: "model", rating: "unknown", basis: "none", note: "Not needed for an internal tool." },
      { key: "distribution", rating: "unknown", basis: "none", note: "Not needed yet." },
      { key: "feasibility", rating: "strong", basis: "evidence", note: "Front-end prototype works; SQLite is a small step." },
      { key: "risk", rating: "strong", basis: "judgment", note: "Low downside — originals stay where they are." },
      { key: "nextSteps", rating: "strong", basis: "judgment", note: "Load one real project end to end." },
    ],
    risks: [
      { text: "Becomes a place to organize work instead of doing it.", severity: "high" },
      { text: "Summaries drift out of date if originals change.", severity: "medium" },
    ],
    missing: [
      "Rough count of how many projects exist",
      "Where each original currently lives",
      "Whether this ever needs more than one user",
    ],
    reusableAssetIds: ["prompt-library", "brand-editorial", "dossier-template"],
    recommendation: {
      path: "build",
      confidence: "medium",
      reasons: [
        "Internal tool: you are the customer and the problem shows up weekly.",
        "Each real project added makes shared assets and links more useful.",
        "The external-product idea stays separate and unproven.",
      ],
      wouldChange: [
        "First real intake takes more than 2 hours → simplify before adding views.",
        "You stop opening it within 2 weeks → pause and keep a plain folder index.",
      ],
    },
    nextMove: {
      action: "Run one real project through intake — start with Business Plan & Pilot Results.",
      why: "It has the most evidence, so it will stress-test the evidence ledger hardest.",
      doneWhen: "One real dossier with sources linked and a next move you'd actually act on.",
      timebox: "90 min",
    },
    log: [
      { date: "2026-09-18", type: "created", text: "Requirements pulled together from three chats." },
      { date: "2026-09-22", type: "decision", text: "Originals stay outside the app; Vault stores metadata and links only." },
      { date: "2026-09-24", type: "milestone", text: "First prototype: Vault Map + Dossier." },
    ],
    orbit: { ring: 0, angle: 90 },
    sample: true,
  },

  /* ---------------------------------------------------------------- */
  {
    id: "portfolio",
    index: 2,
    name: "Creative Studio Portfolio",
    oneLiner: "A dark, editorial portfolio that presents studio work as case studies, not screenshots.",
    category: "Portfolio",
    area: "Creative",
    status: "Prototyping",
    readiness: 3,
    potential: 3,
    strategic: 5,
    cover: img("portfolio"),
    orb: orb("orb-portfolio"),
    media: [{ id: "m-port-1", projectId: "portfolio", type: "screenshot", src: img("portfolio"), caption: "Homepage draft" }],
    sources: [
      { id: "s-port-1", projectId: "portfolio", kind: "folder", label: "Case study drafts", location: "~/Studio/portfolio-2026/", isSourceOfTruth: true, lastVerified: "2026-09-12" },
      { id: "s-port-2", projectId: "portfolio", kind: "git", label: "Hero scroll prototype", location: "github.com/your-handle/studio-portfolio", isSourceOfTruth: true, lastVerified: "2026-09-12" },
      { id: "s-port-3", projectId: "portfolio", kind: "design", label: "Framer — “Studio v3”", location: "framer.com · staging", isSourceOfTruth: true, lastVerified: "2026-08-21" },
      { id: "s-port-4", projectId: "portfolio", kind: "chat", label: "Claude — “Case study structure”", location: "claude.ai · May 2026", isSourceOfTruth: false, lastVerified: "2026-09-12" },
    ],
    whatItIs: "Studio site with six case studies, a scroll-driven hero and a clear contact path.",
    audience: "Prospective clients hiring for landing pages and interactive web work; potential collaborators.",
    problem:
      "Work is scattered across chats, repos and screenshots, so there's nothing to send a prospect that shows range in 60 seconds.",
    whatExists: [
      "Framer homepage draft with scroll-driven hero",
      "3 of 6 case studies drafted (copy only)",
      "GSAP ScrollTrigger hero prototype in local Git repo",
      "Two logo directions",
    ],
    couldBecome: "The front door for client work and the showcase for every other project.",
    decisionNeeded: "Launch with 3 case studies or wait for 6?",
    evidence: [
      { id: "e-p1", projectId: "portfolio", kind: "prototype", verification: "verified", statement: "Homepage draft live on Framer staging link.", sourceId: "s-port-3", date: "2026-08-21" },
      { id: "e-p2", projectId: "portfolio", kind: "prototype", verification: "verified", statement: "Hero scroll prototype runs locally (commit a3f9e1).", sourceId: "s-port-2", date: "2026-04-18" },
      { id: "e-p3", projectId: "portfolio", kind: "feedback", verification: "claimed", statement: "Two peers said the hero “feels premium” (verbal, not recorded).", date: "2026-08-24" },
      { id: "e-p4", projectId: "portfolio", kind: "feedback", verification: "assumed", statement: "Prospects prefer case studies over a gallery grid.", date: "2026-06-09" },
    ],
    opportunity: {
      summary: "Indirect value: wins client work and makes every other project legible.",
      model: "Supports service revenue (Landing Page Sprint).",
      distribution: "Direct outreach to past contacts; linked from proposals.",
      differentiation: "Case-study storytelling with interaction craft most local studios don't show.",
    },
    stress: [
      { key: "problem", rating: "strong", basis: "judgment", note: "No single link to send prospects today." },
      { key: "audience", rating: "partial", basis: "judgment", note: "Ideal client type not yet chosen." },
      { key: "proof", rating: "weak", basis: "evidence", note: "Artifacts exist; no visitor or client reaction logged." },
      { key: "differentiation", rating: "partial", basis: "judgment", note: "Strong craft; positioning copy unwritten." },
      { key: "scope", rating: "partial", basis: "judgment", note: "Six case studies before launch is a stall risk." },
      { key: "model", rating: "partial", basis: "judgment", note: "Indirect — feeds services." },
      { key: "distribution", rating: "weak", basis: "none", note: "No plan beyond “share it.”" },
      { key: "feasibility", rating: "strong", basis: "evidence", note: "Hero and draft already built." },
      { key: "risk", rating: "strong", basis: "judgment", note: "Low downside." },
      { key: "nextSteps", rating: "strong", basis: "judgment", note: "Publish with three." },
    ],
    risks: [
      { text: "Perfectionism: waiting for six case studies delays launch indefinitely.", severity: "high" },
      { text: "Heavy scroll effects hurt performance on mid-range phones.", severity: "medium" },
    ],
    missing: [
      "Which client type you want most — decides which case study leads",
      "Performance numbers on a mid-range phone",
      "Permission to show pilot client work",
    ],
    reusableAssetIds: ["effect-kit", "brand-editorial"],
    recommendation: {
      path: "portfolio",
      confidence: "high",
      reasons: [
        "Its job is to be seen, not sold — it is the showcase for other projects.",
        "A finished artifact exists (L1), which is the bar for this path.",
        "Case studies can draw directly from Pilot Results and Effect Extractor.",
      ],
      wouldChange: [
        "A prospect asks to buy the effect system → consider Package.",
        "Case studies stall for 30 days → ship with three, not six.",
      ],
    },
    nextMove: {
      action: "Publish with the 3 finished case studies and send the link to 5 past contacts.",
      why: "A live link collects real reactions; drafts collect none.",
      doneWhen: "Public URL live, 5 messages sent, replies logged here.",
      timebox: "1 week",
    },
    log: [
      { date: "2026-03-02", type: "created", text: "Portfolio notes consolidated from three Claude chats." },
      { date: "2026-04-18", type: "milestone", text: "Hero scroll prototype working locally." },
      { date: "2026-06-09", type: "decision", text: "Cut case studies from 8 to 6." },
      { date: "2026-08-21", type: "note", text: "Framer draft reviewed — mobile hero stutters." },
    ],
    orbit: { ring: 0, angle: 0 },
    sample: true,
  },

  /* ---------------------------------------------------------------- */
  {
    id: "extractor",
    index: 3,
    name: "Website Effect Extractor",
    oneLiner:
      "Point it at a site with an effect you love; get a documented, rebuildable pattern — not copied code.",
    category: "Dev Tool",
    area: "Technology",
    status: "Exploring",
    readiness: 2,
    potential: 4,
    strategic: 3,
    cover: img("extractor"),
    orb: orb("orb-extractor"),
    media: [{ id: "m-ext-1", projectId: "extractor", type: "screenshot", src: img("extractor"), caption: "Layer capture view" }],
    sources: [
      { id: "s-ext-1", projectId: "extractor", kind: "git", label: "Capture script", location: "~/Code/effect-extractor/", isSourceOfTruth: true, lastVerified: "2026-09-05" },
      { id: "s-ext-2", projectId: "extractor", kind: "doc", label: "Effect taxonomy notes", location: "~/Studio/research/effects.md", isSourceOfTruth: true, lastVerified: "2026-09-05" },
      { id: "s-ext-3", projectId: "extractor", kind: "chat", label: "ChatGPT — “Rebuild spec prompt”", location: "chatgpt.com · Jul 2026", isSourceOfTruth: false, lastVerified: "2026-09-05" },
    ],
    whatItIs: "A capture script plus prompt that records scroll-linked changes and outputs a GSAP rebuild spec.",
    audience: "Front-end designers and developers building interactive landing pages — and you, for the Effect Kit.",
    problem:
      "Recreating an effect you've seen takes hours in DevTools, and copying code raises licensing problems.",
    whatExists: [
      "Node script that records scroll-linked style changes (works on 4 of 7 test sites)",
      "Notes on 12 effect types — parallax, pinning, text reveals…",
      "Prompt that turns recordings into a GSAP rebuild spec",
    ],
    couldBecome: "A paid dev tool, a browser extension, or simply the engine behind your Effect Kit.",
    decisionNeeded: "Is this a product, or an internal tool?",
    evidence: [
      { id: "e-x1", projectId: "extractor", kind: "prototype", verification: "verified", statement: "Script captured scroll timelines on 4 of 7 test sites.", sourceId: "s-ext-1", date: "2026-09-05" },
      { id: "e-x2", projectId: "extractor", kind: "research", verification: "verified", statement: "Effect taxonomy notes covering 12 types.", sourceId: "s-ext-2", date: "2026-08-14" },
      { id: "e-x3", projectId: "extractor", kind: "feedback", verification: "claimed", statement: "A developer on Discord said they'd “totally use this” (screenshot not saved).", date: "2026-08-30" },
      { id: "e-x4", projectId: "extractor", kind: "feedback", verification: "assumed", statement: "People will pay rather than dig through DevTools themselves.", date: "2026-08-30" },
    ],
    opportunity: {
      summary: "Real pain for a niche audience; unclear whether they pay.",
      model: "Unknown — options: one-time license, subscription, or free tool driving service work.",
      distribution: "Demo videos in front-end communities.",
      differentiation: "Outputs a documented pattern, not scraped source code.",
    },
    stress: [
      { key: "problem", rating: "partial", basis: "evidence", note: "Your own repeated pain; others unconfirmed." },
      { key: "audience", rating: "partial", basis: "judgment", note: "Front-end devs — but which ones?" },
      { key: "proof", rating: "weak", basis: "evidence", note: "Zero outside users." },
      { key: "differentiation", rating: "unknown", basis: "none", note: "No competitor scan yet." },
      { key: "scope", rating: "weak", basis: "judgment", note: "Twelve effect types is too many for v1." },
      { key: "model", rating: "unknown", basis: "none", note: "Not explored." },
      { key: "distribution", rating: "partial", basis: "judgment", note: "Demo-friendly, visual output." },
      { key: "feasibility", rating: "partial", basis: "evidence", note: "Works on 4/7 sites; canvas/WebGL not captured." },
      { key: "risk", rating: "weak", basis: "judgment", note: "IP and terms-of-service questions open." },
      { key: "nextSteps", rating: "strong", basis: "judgment", note: "Five user sessions." },
    ],
    risks: [
      { text: "Legal/ToS exposure if output reproduces proprietary code.", severity: "high" },
      { text: "Canvas and WebGL effects can't be captured this way.", severity: "medium" },
      { text: "Existing tools may already cover this.", severity: "medium" },
    ],
    missing: [
      "Competitor scan",
      "Which 3 effect types matter most to users",
      "Legal read on the “pattern, not code” approach",
    ],
    reusableAssetIds: ["effect-kit", "prompt-library"],
    recommendation: {
      path: "validate",
      confidence: "medium",
      reasons: [
        "The technical core partly works (4/7 sites) — feasibility isn't the main question.",
        "No one outside you has used it, so demand is unproven.",
        "Competition and IP questions are still open.",
      ],
      wouldChange: [
        "3 of 5 target users use it twice in a week → Build.",
        "A mature free tool already exists → keep it as an internal kit only.",
      ],
    },
    nextMove: {
      action: "Record a 90-second demo and have 5 front-end devs try it on a site of their choice.",
      why: "Watching strangers use it answers demand and usability in one step.",
      doneWhen: "5 sessions logged: what they tried, what broke, would they use it again.",
      timebox: "2 weeks",
    },
    log: [
      { date: "2026-07-11", type: "created", text: "Idea captured after rebuilding a pinned-scroll effect by hand." },
      { date: "2026-08-14", type: "evidence", text: "Taxonomy of 12 effect types written." },
      { date: "2026-09-05", type: "milestone", text: "Capture script works on 4 of 7 test sites." },
    ],
    orbit: { ring: 1, angle: 315 },
    sample: true,
  },

  /* ---------------------------------------------------------------- */
  {
    id: "nonprofit",
    index: 4,
    name: "Community Tech Lab",
    oneLiner: "Free evening workshops where local teens build real websites for neighborhood organizations.",
    category: "Nonprofit",
    area: "Nonprofit",
    status: "Piloting",
    readiness: 3,
    potential: 3,
    strategic: 4,
    cover: img("nonprofit"),
    orb: orb("orb-nonprofit"),
    media: [{ id: "m-np-1", projectId: "nonprofit", type: "image", src: img("nonprofit"), caption: "Pilot cohort, week 4" }],
    sources: [
      { id: "s-np-1", projectId: "nonprofit", kind: "drive", label: "Pilot folder", location: "Google Drive / Tech Lab / Pilot 1", isSourceOfTruth: true, lastVerified: "2026-09-15" },
      { id: "s-np-2", projectId: "nonprofit", kind: "doc", label: "6-week curriculum", location: "Google Docs · Curriculum v2", isSourceOfTruth: true, lastVerified: "2026-09-15" },
      { id: "s-np-3", projectId: "nonprofit", kind: "doc", label: "Exit survey export", location: "Drive / Pilot 1 / survey.csv", isSourceOfTruth: true, lastVerified: "2026-09-15" },
    ],
    whatItIs: "A 6-week program pairing teens with volunteer mentors to build sites for local organizations.",
    audience:
      "Teens 14–18 without access to coding programs; small local organizations that need a basic website; sponsors wanting visible community impact.",
    problem:
      "Teens lack hands-on portfolio work and small local organizations lack websites — one program can address both.",
    whatExists: [
      "6-week pilot curriculum",
      "Pilot cohort: 14 enrolled, 2 volunteer mentors",
      "3 student-built sites now used by local organizations",
      "Draft partnership one-pager",
    ],
    couldBecome: "A recurring, sponsor-funded program hosted by the library, running two cohorts a year.",
    decisionNeeded: "Pitch partners now, or run a second self-funded cohort first?",
    evidence: [
      { id: "e-n1", projectId: "nonprofit", kind: "pilot", verification: "verified", statement: "Pilot ran 6 weeks: 14 enrolled, 11 finished (attendance sheet).", sourceId: "s-np-1", date: "2026-06-28" },
      { id: "e-n2", projectId: "nonprofit", kind: "usage", verification: "verified", statement: "3 local organizations now use student-built sites.", sourceId: "s-np-1", date: "2026-07-15" },
      { id: "e-n3", projectId: "nonprofit", kind: "feedback", verification: "verified", statement: "Exit survey: 9 of 11 students would return.", sourceId: "s-np-3", date: "2026-06-30" },
      { id: "e-n4", projectId: "nonprofit", kind: "partnership", verification: "claimed", statement: "Library director “interested” in hosting cohort 2 (verbal only).", date: "2026-08-12" },
      { id: "e-n5", projectId: "nonprofit", kind: "revenue", verification: "assumed", statement: "Local businesses will sponsor at $500–$2,500.", date: "2026-08-12" },
    ],
    opportunity: {
      summary: "Documented pilot, dual impact story, and a warm partner lead.",
      model: "Sponsor-funded; host partner provides space.",
      distribution: "School counselor referrals filled the pilot.",
      differentiation: "Students ship real sites for real organizations — not practice projects.",
    },
    stress: [
      { key: "problem", rating: "strong", basis: "evidence", note: "Pilot filled through referrals." },
      { key: "audience", rating: "strong", basis: "evidence", note: "Students, orgs and sponsors all identified." },
      { key: "proof", rating: "partial", basis: "evidence", note: "One cohort; no 3-month outcomes yet." },
      { key: "differentiation", rating: "partial", basis: "judgment", note: "Real-client model is distinctive locally." },
      { key: "scope", rating: "strong", basis: "judgment", note: "Six weeks, one room, clear deliverable." },
      { key: "model", rating: "weak", basis: "judgment", note: "Sponsor model untested." },
      { key: "distribution", rating: "partial", basis: "evidence", note: "Counselor referrals worked once." },
      { key: "feasibility", rating: "strong", basis: "evidence", note: "Already run once." },
      { key: "risk", rating: "partial", basis: "judgment", note: "Depends on two volunteers." },
      { key: "nextSteps", rating: "strong", basis: "judgment", note: "Get the library commitment in writing." },
    ],
    risks: [
      { text: "Program depends on two volunteer mentors.", severity: "high" },
      { text: "Youth programs need safety policies and background checks.", severity: "high" },
      { text: "No fiscal sponsor or 501(c)(3) status yet.", severity: "medium" },
    ],
    missing: [
      "Legal structure: fiscal sponsor vs. own 501(c)(3)",
      "Cost per student",
      "Outcomes 3 months after the pilot",
    ],
    reusableAssetIds: ["pitch-templates", "impact-sheet", "curriculum"],
    recommendation: {
      path: "pitch",
      confidence: "medium",
      reasons: [
        "Pilot results are documented (L3) — the bar partners expect.",
        "Clear dual impact: students gain work, organizations gain sites.",
        "Funding and space are the constraint, not demand.",
      ],
      wouldChange: [
        "No partner commits within 60 days → run a smaller self-funded cohort 2.",
        "Library confirms in writing → move to Build (cohort 2 plan).",
      ],
    },
    nextMove: {
      action: "Turn pilot data into a one-page impact sheet and request 20 minutes with the library director.",
      why: "Verbal interest is the closest thing to a commitment — get it in writing.",
      doneWhen: "Meeting held and outcome logged: yes, no, or conditions.",
      timebox: "10 days",
    },
    log: [
      { date: "2026-04-20", type: "created", text: "Program outline drafted with two mentors." },
      { date: "2026-05-18", type: "milestone", text: "Pilot cohort began — 14 students." },
      { date: "2026-06-28", type: "evidence", text: "Pilot complete: 11 of 14 finished." },
      { date: "2026-08-12", type: "note", text: "Library director expressed interest (verbal)." },
    ],
    orbit: { ring: 1, angle: 45 },
    sample: true,
  },

  /* ---------------------------------------------------------------- */
  {
    id: "sponsorship",
    index: 5,
    name: "Sponsorship Template System",
    oneLiner: "Sponsor decks, tier sheets and follow-up emails that turn “we need sponsors” into a two-hour task.",
    category: "Template System",
    area: "Business",
    status: "Active",
    readiness: 4,
    potential: 3,
    strategic: 3,
    cover: img("sponsorship"),
    orb: orb("orb-sponsorship"),
    orbScale: 1.45,
    media: [{ id: "m-sp-1", projectId: "sponsorship", type: "image", src: img("sponsorship"), caption: "Printed kit" }],
    sources: [
      { id: "s-sp-1", projectId: "sponsorship", kind: "design", label: "Figma — Sponsor Kit", location: "figma.com · Sponsor Kit v2", isSourceOfTruth: true, lastVerified: "2026-09-02" },
      { id: "s-sp-2", projectId: "sponsorship", kind: "drive", label: "Event uses + signed agreement", location: "Google Drive / Sponsorships", isSourceOfTruth: true, lastVerified: "2026-09-02" },
      { id: "s-sp-3", projectId: "sponsorship", kind: "doc", label: "Tier calculator", location: "Google Sheets · Tier Calculator", isSourceOfTruth: true, lastVerified: "2026-09-02" },
    ],
    whatItIs: "A 12-slide deck template, three tier-sheet variants, a four-email sequence and a pricing calculator.",
    audience: "Small event organizers, nonprofits and community programs seeking local sponsors.",
    problem: "Organizers rebuild sponsor decks from scratch every time and routinely underprice tiers.",
    whatExists: [
      "Figma deck (12 slides) + 3 tier-sheet variants",
      "Four-message email sequence",
      "Tier pricing calculator",
      "Used for 2 events",
    ],
    couldBecome: "A $49–$149 digital kit, or a lead magnet for done-for-you sponsorship services.",
    decisionNeeded: "Sell it as a product or use it to win service work?",
    evidence: [
      { id: "e-s1", projectId: "sponsorship", kind: "usage", verification: "verified", statement: "Kit used for 2 events (files in Drive).", sourceId: "s-sp-2", date: "2026-07-20" },
      { id: "e-s2", projectId: "sponsorship", kind: "usage", verification: "verified", statement: "One sponsor secured at $2,500 using the kit — revenue for the event, not for the kit.", sourceId: "s-sp-2", date: "2026-08-03" },
      { id: "e-s3", projectId: "sponsorship", kind: "feedback", verification: "claimed", statement: "Another organizer asked to buy a copy (text message).", date: "2026-08-19" },
      { id: "e-s4", projectId: "sponsorship", kind: "revenue", verification: "assumed", statement: "Organizers will pay $49–$149 for the kit.", date: "2026-08-19" },
    ],
    opportunity: {
      summary: "Mostly built; packaging takes days. Willingness to pay for the kit itself is unproven.",
      model: "One-time digital purchase; optional customization upsell.",
      distribution: "Unknown — organizer communities, nonprofit networks.",
      differentiation: "Includes pricing logic and follow-ups, not just slide design.",
    },
    stress: [
      { key: "problem", rating: "strong", basis: "evidence", note: "Rebuilt twice before the kit existed." },
      { key: "audience", rating: "partial", basis: "evidence", note: "Two organizers; broader segment untested." },
      { key: "proof", rating: "partial", basis: "evidence", note: "Worked in use; no one has paid for it." },
      { key: "differentiation", rating: "weak", basis: "judgment", note: "Many free templates exist." },
      { key: "scope", rating: "strong", basis: "judgment", note: "Small and finished." },
      { key: "model", rating: "partial", basis: "judgment", note: "Low price needs volume." },
      { key: "distribution", rating: "weak", basis: "none", note: "No channel identified." },
      { key: "feasibility", rating: "strong", basis: "evidence", note: "Built." },
      { key: "risk", rating: "strong", basis: "judgment", note: "Cheap to test." },
      { key: "nextSteps", rating: "strong", basis: "judgment", note: "Put a price on it." },
    ],
    risks: [
      { text: "Crowded market of free templates.", severity: "high" },
      { text: "Low price point requires volume you don't have a channel for.", severity: "medium" },
    ],
    missing: ["Whether buyers want files or a service", "Where organizers look for templates"],
    reusableAssetIds: ["pitch-templates", "impact-sheet", "email-sequence"],
    recommendation: {
      path: "package",
      confidence: "medium",
      reasons: [
        "The kit produced a real outcome in use (L3): a $2,500 sponsor.",
        "It's mostly built — packaging is days, not months.",
        "Willingness to pay for the kit itself is still unproven, so keep the test small.",
      ],
      wouldChange: [
        "0 of 10 organizers buy at $49 → make it a free lead magnet for services.",
        "Buyers ask for customization → offer a done-for-you service instead.",
      ],
    },
    nextMove: {
      action: "Put the kit on a simple $49 checkout page and send it to the organizer who asked, plus 9 others.",
      why: "One real purchase settles more than any pricing debate.",
      doneWhen: "10 people contacted; purchases and objections logged.",
      timebox: "1 week",
    },
    log: [
      { date: "2026-05-02", type: "created", text: "Deck rebuilt for the second time — turned into a template." },
      { date: "2026-07-20", type: "evidence", text: "Used for a second event." },
      { date: "2026-08-03", type: "evidence", text: "$2,500 sponsor signed using the kit." },
    ],
    orbit: { ring: 1, angle: 135 },
    sample: true,
  },

  /* ---------------------------------------------------------------- */
  {
    id: "pilot",
    index: 6,
    name: "Business Plan & Pilot Results",
    oneLiner: "A fixed-price, two-week landing-page sprint for local businesses — tested with paying pilot clients.",
    category: "Business Pilot",
    area: "Business",
    status: "Piloting",
    readiness: 4,
    potential: 4,
    strategic: 5,
    cover: img("pilot"),
    orb: orb("orb-pilot"),
    media: [{ id: "m-pi-1", projectId: "pilot", type: "image", src: img("pilot"), caption: "Plan v2 and pilot report" }],
    sources: [
      { id: "s-pi-1", projectId: "pilot", kind: "doc", label: "Business plan v2", location: "~/Business/sprint/plan-v2.pdf", isSourceOfTruth: true, lastVerified: "2026-09-18" },
      { id: "s-pi-2", projectId: "pilot", kind: "folder", label: "Pilot client folders + invoices", location: "~/Business/sprint/pilot/", isSourceOfTruth: true, lastVerified: "2026-09-18" },
      { id: "s-pi-3", projectId: "pilot", kind: "doc", label: "Testimonials", location: "~/Business/sprint/testimonials.md", isSourceOfTruth: true, lastVerified: "2026-09-18" },
      { id: "s-pi-4", projectId: "pilot", kind: "chat", label: "ChatGPT — “Pricing model v2”", location: "chatgpt.com · Jun 2026", isSourceOfTruth: false, lastVerified: "2026-09-18" },
    ],
    whatItIs: "An 18-page plan plus a 6-client pilot of a productized landing-page service.",
    audience: "Local service businesses — salons, contractors, clinics — with outdated or missing websites.",
    problem:
      "Small businesses get quotes measured in months and thousands of dollars; they need something good, fast and fixed-price.",
    whatExists: [
      "Business plan v2 with pricing and cost model",
      "Pilot: 6 clients delivered, 4 paid",
      "Two written testimonials",
      "Proposal and onboarding templates",
    ],
    couldBecome: "Your core revenue engine, feeding case studies to the portfolio.",
    decisionNeeded: "Scale at full price, or run a second discounted pilot?",
    evidence: [
      { id: "e-b1", projectId: "pilot", kind: "revenue", verification: "verified", statement: "4 of 6 pilot clients paid — $3,200 total (invoices).", sourceId: "s-pi-2", date: "2026-08-30" },
      { id: "e-b2", projectId: "pilot", kind: "pilot", verification: "verified", statement: "6-client pilot delivered on the two-week format.", sourceId: "s-pi-2", date: "2026-08-30" },
      { id: "e-b3", projectId: "pilot", kind: "feedback", verification: "verified", statement: "Two written testimonials.", sourceId: "s-pi-3", date: "2026-09-04" },
      { id: "e-b4", projectId: "pilot", kind: "usage", verification: "claimed", statement: "Clients say inquiries roughly doubled — no analytics access to confirm.", date: "2026-09-10" },
      { id: "e-b5", projectId: "pilot", kind: "revenue", verification: "assumed", statement: "Can sell 4 sprints a month at $1,200.", date: "2026-09-12" },
    ],
    opportunity: {
      summary: "The only project with paying customers. The open question is full-price, non-referral demand.",
      model: "Fixed-price sprint ($800 pilot → $1,200 target) + optional care plan.",
      distribution: "All 6 pilot clients came from referrals; cold outreach untested.",
      differentiation: "Speed and a fixed price vs. agencies; craft vs. cheap freelancers.",
    },
    stress: [
      { key: "problem", rating: "strong", basis: "evidence", note: "Clients paid to solve it." },
      { key: "audience", rating: "strong", basis: "evidence", note: "Six real businesses in segment." },
      { key: "proof", rating: "strong", basis: "evidence", note: "$3,200 invoiced and paid." },
      { key: "differentiation", rating: "partial", basis: "judgment", note: "Freelancers compete on price." },
      { key: "scope", rating: "strong", basis: "evidence", note: "Two-week format held in pilot." },
      { key: "model", rating: "partial", basis: "evidence", note: "Pilot was discounted 33%." },
      { key: "distribution", rating: "partial", basis: "evidence", note: "Referral-only so far." },
      { key: "feasibility", rating: "strong", basis: "evidence", note: "Delivered six times." },
      { key: "risk", rating: "partial", basis: "judgment", note: "Your hours are the bottleneck." },
      { key: "nextSteps", rating: "strong", basis: "judgment", note: "Test full price." },
    ],
    risks: [
      { text: "All clients came from personal referrals — cold demand untested.", severity: "high" },
      { text: "Pilot price was discounted 33%.", severity: "medium" },
      { text: "Delivery depends entirely on your hours.", severity: "medium" },
    ],
    missing: [
      "Actual hours per sprint (only estimated)",
      "Analytics access to verify inquiry claims",
      "Maintenance / care-plan terms",
    ],
    reusableAssetIds: ["pitch-templates", "effect-kit"],
    recommendation: {
      path: "build",
      confidence: "high",
      reasons: [
        "Only project with paying customers (L4): $3,200 from 4 clients.",
        "Unit economics in the plan can be tested within a month.",
        "Feeds Portfolio case studies and reuses the proposal templates.",
      ],
      wouldChange: [
        "Fewer than 2 full-price sprints close in 30 days → revisit offer or price.",
        "Delivery exceeds 25 hours per sprint → narrow scope before scaling.",
      ],
    },
    nextMove: {
      action: "Set the price at $1,200 and pitch 10 local businesses using the two testimonials.",
      why: "The pilot proved people pay at a discount; the open question is full-price demand.",
      doneWhen: "10 pitches sent; closes and objections logged here.",
      timebox: "3 weeks",
    },
    log: [
      { date: "2026-05-10", type: "created", text: "Business plan v1 drafted with ChatGPT; revised to v2." },
      { date: "2026-06-15", type: "decision", text: "Pilot at $800 for first 6 clients." },
      { date: "2026-08-30", type: "evidence", text: "Pilot complete — 4 of 6 paid, $3,200." },
      { date: "2026-09-04", type: "evidence", text: "Two testimonials received in writing." },
    ],
    orbit: { ring: 0, angle: 180 },
    sample: true,
  },

  /* ---------------------------------------------------------------- */
  {
    id: "aiconcepts",
    index: 7,
    name: "Experimental AI App Concepts",
    oneLiner: "Five early AI app ideas parked in one place, each with a kill test instead of a build plan.",
    category: "AI Concepts",
    area: "Technology",
    status: "Idea",
    readiness: 1,
    potential: 3,
    strategic: 2,
    cover: img("aiconcepts"),
    orb: orb("orb-aiconcepts"),
    media: [{ id: "m-ai-1", projectId: "aiconcepts", type: "image", src: img("aiconcepts"), caption: "Concept wall" }],
    sources: [
      { id: "s-ai-1", projectId: "aiconcepts", kind: "chat", label: "Claude — 4 concept threads", location: "claude.ai · Feb–Aug 2026", isSourceOfTruth: true, lastVerified: "2026-09-01" },
      { id: "s-ai-2", projectId: "aiconcepts", kind: "chat", label: "ChatGPT — “Brief Decoder”", location: "chatgpt.com · Jul 2026", isSourceOfTruth: true, lastVerified: "2026-09-01" },
      { id: "s-ai-3", projectId: "aiconcepts", kind: "design", label: "Figma — Prompt Remix mockup", location: "figma.com · Prompt Remix", isSourceOfTruth: true, lastVerified: "2026-09-01" },
    ],
    whatItIs:
      "Prompt Remix, Client Brief Decoder, Pitch Rehearsal Coach, Screenshot-to-Spec and Grant Match Notes.",
    audience: "Varies by concept — not defined for any single one yet.",
    problem:
      "Ideas arrive faster than they can be tested, and each one pulls focus from projects that have evidence.",
    whatExists: [
      "5 concept notes spread across chats",
      "1 clickable mockup (Prompt Remix)",
      "Moodboard of 20 interface references",
    ],
    couldBecome: "One validated concept — or useful features absorbed into other projects.",
    decisionNeeded: "Which, if any, deserves validation time?",
    evidence: [
      { id: "e-a1", projectId: "aiconcepts", kind: "prototype", verification: "verified", statement: "Clickable Prompt Remix mockup.", sourceId: "s-ai-3", date: "2026-07-28" },
      { id: "e-a2", projectId: "aiconcepts", kind: "revenue", verification: "assumed", statement: "At least one concept could become a paid tool.", date: "2026-08-10" },
      { id: "e-a3", projectId: "aiconcepts", kind: "feedback", verification: "assumed", statement: "AI features make these differentiated.", date: "2026-08-10" },
    ],
    opportunity: {
      summary: "Optionality, not opportunity — nothing is tested.",
      model: "Undefined.",
      distribution: "Undefined.",
      differentiation: "Unclear; AI features commoditize quickly.",
    },
    stress: [
      { key: "problem", rating: "weak", basis: "judgment", note: "Problems are guesses per concept." },
      { key: "audience", rating: "unknown", basis: "none", note: "None defined." },
      { key: "proof", rating: "weak", basis: "evidence", note: "One mockup." },
      { key: "differentiation", rating: "unknown", basis: "none", note: "No scan." },
      { key: "scope", rating: "weak", basis: "judgment", note: "Five ideas at once." },
      { key: "model", rating: "unknown", basis: "none", note: "—" },
      { key: "distribution", rating: "unknown", basis: "none", note: "—" },
      { key: "feasibility", rating: "partial", basis: "judgment", note: "Buildable with current tools." },
      { key: "risk", rating: "partial", basis: "judgment", note: "Main risk is lost focus." },
      { key: "nextSteps", rating: "strong", basis: "judgment", note: "Write kill tests, then park." },
    ],
    risks: [
      { text: "Pulls focus from evidence-backed projects.", severity: "high" },
      { text: "AI features commoditize quickly.", severity: "medium" },
    ],
    missing: ["A target user for each concept", "Which concepts overlap existing work"],
    reusableAssetIds: ["prompt-library"],
    recommendation: {
      path: "pause",
      confidence: "high",
      reasons: [
        "No concept has a defined user or any outside signal (L1 at most).",
        "Pilot Results and Community Tech Lab have stronger evidence and need your time now.",
        "Parking with a kill test keeps the ideas without letting them sprawl.",
      ],
      wouldChange: [
        "A real person asks for one of these by name → move that concept to Validate.",
        "Effect Extractor validates → Screenshot-to-Spec may merge into it.",
      ],
    },
    nextMove: {
      action: "Write a one-sentence kill test for each concept, then leave them alone for 60 days.",
      why: "It turns a vague backlog into a clear revisit rule.",
      doneWhen: "5 kill tests written; revisit date set for Nov 23.",
      timebox: "30 min",
    },
    log: [
      { date: "2026-02-14", type: "created", text: "First concept (Prompt Remix) sketched in Claude." },
      { date: "2026-07-28", type: "milestone", text: "Prompt Remix clickable mockup." },
      { date: "2026-09-01", type: "decision", text: "All five concepts gathered into one entry." },
    ],
    orbit: { ring: 1, angle: 225 },
    sample: true,
  },
];

export const connections: Connection[] = [
  { id: "c1", from: "portfolio", to: "extractor", type: "technology", label: "GSAP scroll effects" },
  { id: "c2", from: "portfolio", to: "vault", type: "style", label: "Dark editorial visual language" },
  { id: "c3", from: "vault", to: "aiconcepts", type: "technology", label: "AI-assisted analysis" },
  { id: "c4", from: "vault", to: "extractor", type: "opportunity", label: "Extracted effects feed the Asset Library" },
  { id: "c5", from: "extractor", to: "aiconcepts", type: "technology", label: "Screenshot-to-Spec overlap" },
  { id: "c6", from: "nonprofit", to: "sponsorship", type: "model", label: "Sponsor-funded programs" },
  { id: "c7", from: "pilot", to: "sponsorship", type: "model", label: "Templates as service add-on" },
  { id: "c8", from: "pilot", to: "nonprofit", type: "audience", label: "Local businesses & community orgs" },
  { id: "c9", from: "portfolio", to: "pilot", type: "opportunity", label: "Pilot results become case studies" },
  { id: "c10", from: "vault", to: "pilot", type: "opportunity", label: "First real dossier" },
  // asset satellites
  { id: "a1", from: "effect-kit", to: "portfolio", type: "asset", label: "Scroll & 3D Effect Kit" },
  { id: "a2", from: "effect-kit", to: "extractor", type: "asset", label: "Scroll & 3D Effect Kit" },
  { id: "a3", from: "effect-kit", to: "pilot", type: "asset", label: "Scroll & 3D Effect Kit" },
  { id: "a4", from: "prompt-library", to: "vault", type: "asset", label: "Prompt Library" },
  { id: "a5", from: "prompt-library", to: "extractor", type: "asset", label: "Prompt Library" },
  { id: "a6", from: "prompt-library", to: "aiconcepts", type: "asset", label: "Prompt Library" },
  { id: "a7", from: "pitch-templates", to: "sponsorship", type: "asset", label: "Pitch & Proposal Templates" },
  { id: "a8", from: "pitch-templates", to: "nonprofit", type: "asset", label: "Pitch & Proposal Templates" },
  { id: "a9", from: "pitch-templates", to: "pilot", type: "asset", label: "Pitch & Proposal Templates" },
];
